# Generated by Django 5.2.9 on 2026-01-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banner",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="galleryimage",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="homecard",
            options={"ordering": ["order"]},
        ),
        migrations.RemoveField(
            model_name="homecard",
            name="text",
        ),
        migrations.AddField(
            model_name="homecard",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="banner",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="homecard",
            name="icon",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="homecard",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="homecard",
            name="title",
            field=models.CharField(max_length=120),
        ),
    ]
