# Generated by Django 5.2.9 on 2026-01-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_alter_banner_options_alter_galleryimage_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homecard",
            options={},
        ),
        migrations.AddField(
            model_name="homecard",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="cards/"),
        ),
        migrations.AlterField(
            model_name="banner",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="homecard",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homecard",
            name="icon",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="homecard",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
