# Generated by Django 5.2.9 on 2026-01-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_coverageamount_quotefactor_quoterequest_premiumrate"),
    ]

    operations = [
        migrations.CreateModel(
            name="TermRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Homem"), ("F", "Mulher")], max_length=1
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                ("coverage", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "ordering": ["gender", "age", "coverage"],
                "unique_together": {("gender", "age", "coverage")},
            },
        ),
    ]
