# Generated by Django 5.2.9 on 2026-02-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_termrate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="termrate",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="termrate",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="termrate",
            name="smoker",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="termrate",
            name="age",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="termrate",
            name="coverage",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="termrate",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=1
            ),
        ),
        migrations.AlterUniqueTogether(
            name="termrate",
            unique_together={("gender", "age", "coverage", "smoker")},
        ),
    ]
