# Generated by Django 5.2.9 on 2026-02-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_alter_termrate_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quoterequest",
            name="smoker",
            field=models.BooleanField(default=True),
        ),
    ]
