# Generated by Django 5.2.9 on 2026-02-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_alter_quoterequest_smoker"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("text", models.TextField()),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="testimonials/"),
                ),
                ("allow_publish", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
