# Generated by Django 5.2.9 on 2026-02-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0009_testimonialvideo"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoTestimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=120)),
                ("youtube_url", models.URLField()),
                ("allow_publish", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
