# Generated by Django 5.2.9 on 2026-02-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0010_videotestimonial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TestimonialVideo",
        ),
        migrations.AlterModelOptions(
            name="termrate",
            options={"ordering": ["gender", "age", "coverage", "smoker"]},
        ),
        migrations.AlterField(
            model_name="quoterequest",
            name="smoker",
            field=models.BooleanField(default=False),
        ),
    ]
