# Generated by Django 5.2.9 on 2026-02-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0011_delete_testimonialvideo_alter_termrate_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Audience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("subtitle", models.CharField(blank=True, max_length=140)),
                ("image", models.ImageField(upload_to="audience/")),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
