# Generated by Django 6.0.1 on 2026-02-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0012_audience"),
    ]

    operations = [
        migrations.AddField(
            model_name="audience",
            name="slug",
            field=models.SlugField(blank=True, max_length=80, null=True, unique=True),
        ),
    ]
