# Generated by Django 6.0.1 on 2026-01-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("subtitle", models.CharField(blank=True, max_length=200)),
                ("image", models.ImageField(upload_to="banners/")),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=120)),
                ("image", models.ImageField(upload_to="gallery/")),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="HomeCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("text", models.CharField(max_length=220)),
                ("icon", models.CharField(default="shield-check", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
