# Generated by Django 5.2.9 on 2026-01-28 00:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_alter_homecard_options_homecard_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoverageAmount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=30, unique=True)),
                ("amount", models.PositiveIntegerField(unique=True)),
            ],
            options={
                "ordering": ["amount"],
            },
        ),
        migrations.CreateModel(
            name="QuoteFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("SMOKER_NO", "Fumante: Não"),
                            ("SMOKER_YES", "Fumante: Sim"),
                            ("HEALTH_OK", "Saúde: Sem problemas"),
                            ("HEALTH_LIGHT", "Saúde: Leve"),
                            ("HEALTH_MED", "Saúde: Moderado"),
                            ("HEALTH_HIGH", "Saúde: Grave"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "multiplier",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=6
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="QuoteRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                (
                    "gender",
                    models.CharField(
                        choices=[("F", "Mulher"), ("M", "Homem")], max_length=1
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(120),
                        ]
                    ),
                ),
                ("smoker", models.BooleanField(default=False)),
                (
                    "health_level",
                    models.CharField(
                        choices=[
                            ("OK", "Sem problemas"),
                            ("LIGHT", "Leve"),
                            ("MED", "Moderado"),
                            ("HIGH", "Grave"),
                        ],
                        default="OK",
                        max_length=10,
                    ),
                ),
                ("health_details", models.TextField(blank=True)),
                (
                    "calculated_monthly",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coverage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="website.coverageamount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PremiumRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("F", "Mulher"), ("M", "Homem")], max_length=1
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(120),
                        ]
                    ),
                ),
                (
                    "monthly_premium",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "coverage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="website.coverageamount",
                    ),
                ),
            ],
            options={
                "ordering": ["gender", "age", "coverage__amount"],
                "unique_together": {("gender", "age", "coverage")},
            },
        ),
    ]
